version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always 

  odoo12:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always   
